-- Notices:
--
-- Copyright 2020 United States Government as represented by the Administrator of the National Aeronautics and Space Administration. All Rights Reserved.
--
-- Disclaimers
-- No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.  FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES IT "AS IS."
--
-- Waiver and Indemnity:  RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT.  IF RECIPIENT'S USE OF THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW.  RECIPIENT'S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL TERMINATION OF THIS AGREEMENT.

{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE FlexibleInstances #-}

module Certificate.Numerical where

import AbsPVSLang hiding (fpGuardList,letExpr,varName)
import AbsSpecLang
import AbstractDomain
import AnalysisResult
import Certificate.Symbolic (f2r,prIsFinite,printFinitenessConditions,prRealFunApp,prDivergence)
import Common.ControlFlow
import Common.DecisionPath
import ErrorResult
import Kodiak.Runner (maximumUpperBound)
import PPExt
import RelativeError (RelError(..))
import Translation.Float2Real (fp2realArg)

import Data.Maybe (fromMaybe)
import Numeric
import Prelude hiding ((<>))

genFpProgFile :: PVSType -> String -> Program -> Doc
genFpProgFile fp progFileName prog =
  text "% This file is automatically generated by PRECiSA \n"
  $$
  text (progFileName ++ ": THEORY")
  $$
  text "BEGIN" <> text "\n"
  $$
  importFPTheory fp <> text "\n"
  $$
  prettyDoc prog <> text "\n"
  $$
  text ("END " ++ progFileName)
    where
      importFPTheory FPSingle = text "IMPORTING float_bounded_axiomatic@ieee754_single"
      importFPTheory FPDouble = text "IMPORTING float_bounded_axiomatic@ieee754_double"
      importFPTheory _ = emptyDoc

-- | Version for Kodiak backend with FunResult (supports relative error)
genNumCertFile :: String
               -> String
               -> [FunResult]
               -> [Decl]
               -> Spec
               -> Int
               -> Int
               -> Bool
               -> Doc
genNumCertFile certFileName numCertFileName kodiakResult decls (Spec specBinds) maxBBDepth prec isTran =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text ("% maxDepth: " ++ show maxBBDepth ++ " , prec: 10^-" ++ show prec ++ "\n")
  $$
  text (numCertFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text ("IMPORTING " ++ certFileName)
  $$
  text "IMPORTING PRECiSA@bbiasp"
  $$
  text "IMPORTING PRECiSA@bbiadp"
  $$
  text "IMPORTING PRECiSA@strategies"
  $$
  text "%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED"
  $$
  text ""
  $$
  printNumCerts kodiakResult decls specBinds maxBBDepth prec isTran
  $$
  text ("END " ++ numCertFileName)

-- | Version for other backends (PVSio) with tuple format (no relative error)
genNumCertFileTuples :: (HasErrorBound result errorType, PrettyError errorType)
               => String
               -> String
               -> [(String,PVSType,[Arg]
                  ,[(ResultField, [(Conditions,LDecisionPath,ControlFlow,result,AExpr,[FAExpr],[AExpr])])])]
               -> [Decl]
               -> Spec
               -> Int
               -> Int
               -> Bool
               -> Doc
genNumCertFileTuples certFileName numCertFileName results decls (Spec specBinds) maxBBDepth prec isTran =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text ("% maxDepth: " ++ show maxBBDepth ++ " , prec: 10^-" ++ show prec ++ "\n")
  $$
  text (numCertFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text ("IMPORTING " ++ certFileName)
  $$
  text "IMPORTING PRECiSA@bbiasp"
  $$
  text "IMPORTING PRECiSA@bbiadp"
  $$
  text "IMPORTING PRECiSA@strategies"
  $$
  text "%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED"
  $$
  text ""
  $$
  printNumCertsTuples results decls specBinds maxBBDepth prec isTran
  $$
  text ("END " ++ numCertFileName)

-- | Print numerical certificates from FunResult (Kodiak backend)
printNumCerts :: [FunResult]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCerts [] _ _ _ _ _ = emptyDoc
printNumCerts (fr:res') decls spec maxBBDepth prec isTran
  | frType fr == Boolean = printNumCerts res' decls spec maxBBDepth prec isTran
  | otherwise =
      printNumCertsField (frName fr) (frType fr) (frArgs fr) (frFields fr) decls spec maxBBDepth prec isTran
      $$
      printNumCerts res' decls spec maxBBDepth prec isTran

-- | Print numerical certificates from tuples (PVSio backend)
printNumCertsTuples :: (HasErrorBound result errorType, PrettyError errorType)
              => [(String,PVSType,[Arg]
                  ,[(ResultField, [(Conditions,LDecisionPath,ControlFlow,result,AExpr,[FAExpr],[AExpr])])])]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCertsTuples [] _ _ _ _ _ = emptyDoc
printNumCertsTuples ((_,Boolean,_,_):_) _ _ _ _ _ = emptyDoc
printNumCertsTuples ((f,fp,args,fSem):res') decls spec maxBBDepth prec isTran =
  printNumCertsFieldTuples f fp args fSem decls spec maxBBDepth prec isTran
  $$
  printNumCertsTuples res' decls spec maxBBDepth prec isTran


printNumCertsField :: String
              -> PVSType
              -> [Arg]
              -> [(ResultField, [PathResult])]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCertsField _ _ _ [] _ _ _ _ _ = emptyDoc
printNumCertsField f t args ((field,res):res') decls spec maxBBDepth prec isTran =
  printNumCertsFun fFP fReal field args res ranges 0 fp prec maxBBDepth isTran fpGuardList
  $$
  printNumCertsField f t args res' decls spec maxBBDepth prec isTran
  where
    fp = case t of
      Tuple ts -> case field of
                      ResTupleIndex idx -> ts !! fromInteger (idx - 1)
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid tuple index."
      Record ts -> case field of
                      ResRecordField rField -> fromMaybe (error $ "printCertsField: field " ++ show rField ++ " not found.")
                                              $ lookup rField ts
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid record field."
      _ -> t
    fpGuardList = case findInDecls f decls of
                     Just (_,_,body@(AExprBody _ae)) -> listFPGuards body
                     Just (_,_,body@(CExprBody _ae)) -> listFPGuards body
                     Just (_,_,BExprBody _) -> error $ "printNumCerts: function " ++ f ++ " is of type Boolean."
                     Nothing -> error $ "printNumCerts: function " ++ f ++ " not found."
    ranges = fromMaybe (error $ "printNumCerts: function " ++ show f ++ " not found.") (findInSpec f spec)
    fFP   = if isTran then f ++ "_fp" else f
    fReal = if isTran then f else f ++ "_real"

printNumCertsFun :: String
                 -> String
                 -> ResultField
                 -> [Arg]
                 -> [PathResult]
                 -> [VarBind]
                 -> Int
                 -> PVSType
                 -> Int
                 -> Int
                 -> Bool
                 -> [FAExpr]
                 -> Doc
printNumCertsFun _ _ _ _ [] _ _ _ _ _ _ _ = emptyDoc
printNumCertsFun f fReal field args (pr:result') ranges n fp prec maxBBDepth isTran fpGuardList =
  prPvsNumLemma numLemma f fReal field args fpResult cond roundOffError ranges fp Nothing fpGuardList
  $$
  prPvsNumProof numLemma symbLemma prec maxBBDepth
  $$
  (case prRelError pr of
     RelErrorBound (RelFinite relBound) ->
       prPvsNumRelLemma numRelLemma f fReal field args cond relBound ranges fp fpGuardList
       $$
       prPvsNumRelProof numRelLemma symbRelLemma relBound prec maxBBDepth
     _ -> emptyDoc)
  $$
  (if isTran
     then prPvsNumLemma auxLemmaName f fReal field args fpResult cond roundOffError ranges fp (Just err) fpGuardList
     else emptyDoc)
  $$
  printNumCertsFun f fReal field args result' ranges (n+1) fp prec maxBBDepth isTran fpGuardList
  where
    cond = prConds pr
    err = prErrExpr pr
    fpResult = prFpExprs pr
    auxLemmaName = name field <> text "_err_" <> int n
    numLemma = name field <> text "_c_" <> int n
    roundOffError = maximumUpperBound (prKodiak pr)
    symbLemma = name field <> text "_" <> int n
    numRelLemma  = name field <> text "_rel_c_" <> int n
    symbRelLemma = name field <> text "_rel_" <> int n
    name ResValue = text f
    name (ResRecordField recField) = text f <> text "_" <> text recField
    name (ResTupleIndex tupleIdx) = text f <> text "_" <> integer tupleIdx

prInfoLemma :: ControlFlow -> [FAExpr] -> [AExpr] -> Doc
prInfoLemma cflow fpes reales = text "% Floating-Point Results:"<+> hsep (punctuate comma $ map prettyDoc fpes)
  $$
  text "% Real Results:"<+> hsep (punctuate comma $ map prettyDoc reales)
  $$
  text "% Control Flow: "<+> prettyDoc cflow

prPvsNumProof :: Doc -> Doc -> Int -> Int -> Doc
prPvsNumProof numLemma symbLemma prec maxBBDepth =
     text "%|-" <+> numLemma <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-concrete-lemma" <+> symbLemma <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

prPvsNumRelLemma :: Doc
                 -> String
                 -> String
                 -> ResultField
                 -> [Arg]
                 -> Conditions
                 -> Double
                 -> [VarBind]
                 -> PVSType
                 -> [FAExpr]
                 -> Doc
prPvsNumRelLemma nameLemma f fReal field args cond relBound ranges fp _fpGuards =
  nameLemma <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args)
                    <>  text ": real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args) <> text ")" <> text ":"
  $$ prPvsArgs args
  $$ (if isTrueCondition cond then empty else text "AND" <+> parens (prettyDoc cond))
  <+> text "AND"
  $$ hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ prDivergence f fReal field args fp
  <+> text "<="
  <+> relBoundDoc <> text "\n"
  where
    relBoundDoc = prettyRatNumError relBound <+> text "*"
                  <+> text "abs(" <> prRealFunApp fReal field args <> text ")"

prPvsNumRelProof :: Doc -> Doc -> Double -> Int -> Int -> Doc
prPvsNumRelProof numLemma symbLemma relBound prec maxBBDepth =
     text "%|-" <+> numLemma <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-relative-lemma" <+> symbLemma
                            <+> doubleQuotes (prettyRatNumError relBound)
                            <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

prPvsNumLemma :: PrettyError errorType
                => Doc
                -> String
                -> String
                -> ResultField
                -> [Arg]
                -> [FAExpr]
                -> Conditions
                -> errorType
                -> [VarBind]
                -> PVSType
                -> Maybe AExpr
                -> [FAExpr]
                -> Doc
prPvsNumLemma nameLemma f fReal field args fpResult cond roundOffError ranges fp symbError _fpGuards =
  nameLemma <+> text ": LEMMA"
  $$ text "FORALL("
    <> prRealParams args
    <> comma
    <+> hsep (punctuate comma $ map prettyDoc args) <> text ")" <> text ":"
  $$
  printFinitenessConditions f args fp fpResult
  $$
  text "AND"
  $$ prPvsArgs args
  $$ (if isTrueCondition cond then empty else text "AND" <+> parens (prettyDoc cond))
  <+> text "AND"
  $$ hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ lhs
  <+> text "<="
  <+> prettyRatNumError roundOffError <> text "\n"
  where
    divergence =  text "abs("
      <>  f2r fp (printNameWithField (text f <> text "("
      <>  hsep (punctuate comma $ map (prettyDoc . arg2var) args) <> text ")") field)
      <+> text "-"
      <+> printNameWithField (text fReal <> text "("
      <>  hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args) <> text ")") field
      <>  text ")"
    lhs = maybe divergence prettyDoc symbError

prRealParams :: [Arg] -> Doc
prRealParams args = hsep $ punctuate comma $ map prParameterWithType args
  where
    prParameterWithType :: Arg -> Doc
    prParameterWithType arg = text rVar <> text ":" <+> prettyDoc rType
      where
        Arg rVar rType = fp2realArg arg

prPvsArgs :: [Arg] -> Doc
prPvsArgs arguments = hsep $ punctuate (text " AND") $ map (uncurry prPVSVarId . mapArg2Pair) arguments

prPVSVarId :: VarName -> PVSType -> Doc
prPVSVarId _ (TypeFun _ _) = empty
prPVSVarId x (Tuple ts) = vcat $ zipWith (curry (uncurry prPVSVarId . tuple2Arg)) ts indexes
  where
    tuple2Arg (idxType, idx) = (x ++ "_" ++ show idx, idxType)
    indexes = [1..] :: [Int]
prPVSVarId x (Record fs) = vcat $ map (uncurry prPVSVarId . record2Arg) fs
  where
    record2Arg (field,fieldType) = (x ++ "_" ++ field, fieldType)
prPVSVarId x TInt = text "abs("<> text x <+> text "-" <+> text "r_" <> text x <> text ")" <> text "<= 0"
prPVSVarId x ty@(ArrayOf _ FPDouble)  = text "l_inf_norm" <> parens (f2r ty (text x)
                       <+> text "-" <+> text "r_" <> text x)
                       <> text "<=" <> prettyDoc (HalfUlp (RealMark x ResValue) ty)
prPVSVarId x fpx  = text "abs(" <> f2r fpx (text x)
                       <+> text "-" <+> text "r_" <> text x <> text ")"
                       <> text "<=" <> prettyDoc (HalfUlp (RealMark x ResValue) fpx)

printVarRange :: VarBind -> Doc
printVarRange (VarBind x ResValue _ lb ub) =
  text "r_" <> text x <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"
printVarRange (VarBind x (ResRecordField field) _ lb ub) =
  text "r_" <> text x <> text "`" <> text field <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"
printVarRange (VarBind x (ResTupleIndex idx) _ lb ub) =
  text "r_" <> text x <> text "`" <> integer idx <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"

-- | Type class for pretty printing error bounds in PVS rational format
-- Supports both Double (Kodiak) and Rational (PVSio) backends
class PrettyError a where
  prettyRatNumError :: a -> Doc

instance PrettyError Double where
  prettyRatNumError roundOffError = text $ showRational (toRational roundOffError)

instance PrettyError Rational where
  prettyRatNumError rat = text $ showRational rat

prettyNumError :: RealFloat a => a -> Doc
prettyNumError roundOffError = text $ showFFloat Nothing roundOffError "" -- (nextUp' roundOffError) ""

genExprCertFile :: PVSType -> String -> String -> String -> Doc -> Doc
genExprCertFile fp inputFileName fpFileName fileName printTranProgPairs =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text (fileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text "IMPORTING" <+> ieeeFormalization fp <> text ", PRECiSA@strategies, PRECiSA@bbiasp, PRECiSA@bbiadp,"
  <+>
  text inputFileName
  <>
  comma
  <+>
  text fpFileName
  $$
  text "\n%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED\n"
  $$
  printTranProgPairs
  $$
  text ("\nEND " ++ fileName)
  where
    ieeeFormalization FPDouble = text "float_bounded_axiomatic@ieee754_double"
    ieeeFormalization FPSingle = text "float_bounded_axiomatic@ieee754_single"
    ieeeFormalization t = error $ "genExprCertFile: PVS type " ++ show t ++ " not supported."

prIsFiniteHpExpr :: [FAExpr] -> Doc
prIsFiniteHpExpr [] = emptyDoc
prIsFiniteHpExpr aes = text "AND"
                       $$ hsep (punctuate (text " AND") (map prIsFinite aes))

printSymbExprCert :: PVSType -> String -> [FAExpr] -> [AExpr] -> [AExpr] -> FAExpr -> AExpr -> FBExpr -> EExpr -> Int -> Doc
printSymbExprCert fp f faeVarList errVarList realVarList fae ae be symbErr n =
  text f <> text "_expr_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prettyVarWithType faeVarList)
                    <> comma
                    <+> hsep (punctuate comma $ map prettyDoc errVarList)
                    <>  text ": nonneg_real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc realVarList)
                    <>  text ": real"
                    <> text ")" <> text ":"
  $$ hsep (punctuate (text " AND") (map (printVarErrBound fp) faeVarList))
  $$ text "AND" <+> parens (prettyDoc be)
  -- $$ prIsFiniteHpExpr (fae:faeVarList)
  $$ text "IMPLIES"
  $$ text "abs(" <> f2r fp (prettyDoc fae)
     <+> text "-"
     <+> prettyDoc ae <> text ")"
     <+> text "<="
     <+> prettyError symbErr
  $$ text "\n%|- " <> text f <> text "_" <> int n <> text ": PROOF"
  $$ text "%|- (precisa)"
  $$ text "%|- QED"
  $$ text "\n"

printNumExprCert :: PrettyError errorType => PVSType -> String -> [FAExpr] -> [AExpr] -> FAExpr -> AExpr -> FBExpr -> errorType -> [VarBind] -> Int -> Int -> Int -> Doc
printNumExprCert fp f faeVarList realVarList fae ae be roundOffError ranges n maxBBDepth prec  =
  text f <> text "_expr_num_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prettyVarWithType faeVarList)
                    <>  comma
                    <+> hsep (punctuate comma $ map prettyDoc realVarList)
                    <>  text ": real"
                    <>  text ")" <> text ":"
  $$ hsep (punctuate (text " AND") $ map (uncurry prPVSVarId . (\a -> (nameFVar a, precFVar a))) faeVarList)
  $$ text "AND"
  <+> parens (prettyDoc be)
  $$ text "AND" <+> hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ text "abs(" <> f2r fp (prettyDoc fae)
     <+> text "-"
     <+> prettyDoc ae <> text ")"
     <+> text "<="
  <> prettyRatNumError roundOffError  <> text "\n"
  $$ text "%|-" <+> text f <> text "_c_" <> int n <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-concrete-lemma" <+> text f <> text "_expr_" <> int n <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

printVarErrBound :: PVSType -> FAExpr -> Doc
printVarErrBound fp var@(FVar _ _) = text "abs(" <> f2r fp (prettyDoc var)
                                                 <> text "-"
                                                 <> prettyDoc (realVar var)
                                                 <> text ")<=" <> prettyDoc (errVar var)
printVarErrBound _ ae = error $ "printVarErrBound: case " ++ show ae ++ " not expected."

printExprFunCert :: (PrettyError errorType, Show errorType) => Int -> Int -> PVSType -> (Decl, [(VarName,FAExpr,AExpr,FBExpr,EExpr,errorType,[FAExpr],[AExpr],[EExpr],[VarBind])]) -> Doc
printExprFunCert maxDepth minPrec fp (Decl _ _ f _ _, exprList) = vcat $ zipWith (printExprCert' maxDepth minPrec fp f) exprList [1 :: Int, 2 ..]
printExprFunCert        _       _ _ (Pred _ TauMinus _ _ _, _) = emptyDoc
printExprFunCert maxDepth minPrec fp (Pred _ _ f _ _, exprList) = vcat $ zipWith (printExprCert' maxDepth minPrec fp f) exprList [1 :: Int, 2 ..]
printExprFunCert _ _ _ x = error $ "[printExprFunCert] Unhandled case: " ++ show x

printExprCert' :: PrettyError errorType => Int -> Int -> PVSType -> String -> (VarName,FAExpr,AExpr,FBExpr,EExpr,errorType,[FAExpr],[AExpr],[EExpr],[VarBind]) -> Int -> Doc
printExprCert' maxDepth minPrec fp f (_,fae, ae, be, symbErr, numErr, faeVarList, realVarList, errVarList,varBinds) n =
  printSymbExprCert fp f faeVarList errVarList realVarList fae ae be symbErr n
  $$
  printNumExprCert fp f faeVarList realVarList fae ae be numErr varBindsRestricted n maxDepth minPrec
  where
    varBindsRestricted = filter (isVarInList (map fvarName faeVarList)) varBinds
    isVarInList vars (VarBind x _ _ _ _) = x `elem` vars

-- | Tuple versions for PVSio backend (no relative error support)
printNumCertsFieldTuples :: (HasErrorBound result errorType, PrettyError errorType)
              => String
              -> PVSType
              -> [Arg]
              -> [(ResultField, [(Conditions,LDecisionPath,ControlFlow,result,AExpr,[FAExpr],[AExpr])])]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCertsFieldTuples _ _ _ [] _ _ _ _ _ = emptyDoc
printNumCertsFieldTuples f t args ((field,res):res') decls spec maxBBDepth prec isTran =
  printNumCertsFunTuples fFP fReal field args res ranges 0 fp prec maxBBDepth isTran fpGuardList
  $$
  printNumCertsFieldTuples f t args res' decls spec maxBBDepth prec isTran
  where
    fp = case t of
      Tuple ts -> case field of
                      ResTupleIndex idx -> ts !! fromInteger (idx - 1)
                      _ -> error $ "printCertsFieldTuples: " ++ show field ++ " is not a valid tuple index."
      Record ts -> case field of
                      ResRecordField rField -> fromMaybe (error $ "printCertsFieldTuples: field " ++ show rField ++ " not found.")
                                              $ lookup rField ts
                      _ -> error $ "printCertsFieldTuples: " ++ show field ++ " is not a valid record field."
      _ -> t
    fpGuardList = case findInDecls f decls of
                     Just (_,_,body@(AExprBody _ae)) -> listFPGuards body
                     Just (_,_,body@(CExprBody _ae)) -> listFPGuards body
                     Just (_,_,BExprBody _) -> error $ "printNumCertsTuples: function " ++ f ++ " is of type Boolean."
                     Nothing -> error $ "printNumCertsTuples: function " ++ f ++ " not found."
    ranges = fromMaybe (error $ "printNumCertsTuples: function " ++ show f ++ " not found.") (findInSpec f spec)
    fFP   = if isTran then f ++ "_fp" else f
    fReal = if isTran then f else f ++ "_real"

printNumCertsFunTuples :: (HasErrorBound result errorType, PrettyError errorType)
                 => String
                 -> String
                 -> ResultField
                 -> [Arg]
                 -> [(Conditions,LDecisionPath,ControlFlow,result,AExpr,[FAExpr],[AExpr])]
                 -> [VarBind]
                 -> Int
                 -> PVSType
                 -> Int
                 -> Int
                 -> Bool
                 -> [FAExpr]
                 -> Doc
printNumCertsFunTuples _ _ _ _ [] _ _ _ _ _ _ _ = emptyDoc
printNumCertsFunTuples f fReal field args ((cond, _, _, res, err, fpResult, _):result') ranges n fp prec maxBBDepth isTran fpGuardList =
  prPvsNumLemma numLemma f fReal field args fpResult cond roundOffError ranges fp Nothing fpGuardList
  $$
  prPvsNumProof numLemma symbLemma prec maxBBDepth
  $$
  (if isTran
     then prPvsNumLemma auxLemmaName f fReal field args fpResult cond roundOffError ranges fp (Just err) fpGuardList
     else emptyDoc)
  $$
  printNumCertsFunTuples f fReal field args result' ranges (n+1) fp prec maxBBDepth isTran fpGuardList
  where
    auxLemmaName = name field <> text "_err_" <> int n
    numLemma = name field <> text "_c_" <> int n
    roundOffError = getErrorUpperBound res
    symbLemma = name field <> text "_" <> int n
    name ResValue = text f
    name (ResRecordField recField) = text f <> text "_" <> text recField
    name (ResTupleIndex tupleIdx) = text f <> text "_" <> integer tupleIdx
