module Certificate.Symbolic where

import AbsPVSLang hiding (fpGuardList,letExpr,varName)
import AbstractDomain
import AbstractSemantics
import Common.TypesUtils (VarName)
import PPExt

import           Data.List (intersperse)
import qualified Data.Map as Map
import           Data.Maybe (fromMaybe)
import           Prelude hiding ((<>))

genCertFile :: String -> String -> String -> Program -> Interpretation -> Doc
genCertFile inputFileName certFileName realFileName prog sem =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text (certFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text "IMPORTING PRECiSA@strategies"
  $$
  text ("IMPORTING " ++ inputFileName)
  $$
  text ("IMPORTING " ++ realFileName  ++ "\n")
  $$
  text "%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED\n"
  $$
  printCerts sem prog
  $$
  text ("END " ++ certFileName)

printCerts :: Interpretation -> Program -> Doc
printCerts interp decls = Map.foldrWithKey printCertsFun emptyDoc interp
  where
    printCertsFun _ (_,Boolean, _, _) certDoc = certDoc
    printCertsFun f (isTrans,t, args, sem) certDoc = case findInDecls f decls of
      Just (_,_,AExprBody stm) -> Map.foldrWithKey (printCertsField f isTrans t stm args) certDoc sem
      _ -> error $ "printCerts: function " ++ show f ++ " not found."

printCertsField :: FunName
                -> Bool
                -> PVSType
                -> FAExpr
                -> [Arg]
                -> ResultField
                -> ACebS
                -> Doc
                -> Doc
printCertsField f isTrans t stm args field cset certDocField
  = printFunctionLemmasAndProofs fFP fReal field args stm cset fp
    $$
    text ""
    $$
    certDocField
  where
    fp = case t of
      Tuple ts -> case field of
                      ResTupleIndex idx -> ts !! fromInteger (idx - 1)
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid tuple index."
      Record ts -> case field of
                      ResRecordField rField -> fromMaybe (error $ "printCertsField: field " ++ show rField ++ " not found.")
                                              $ lookup rField ts
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid record field."
      _ -> t
    fFP   = if isTrans then f ++ "_fp" else f
    fReal = if isTrans then f else f ++ "_real"

printFunctionLemmasAndProofs :: String -> String -> ResultField -> [Arg] -> FAExpr -> ACebS -> PVSType -> Doc
printFunctionLemmasAndProofs f     _     _    _   _    []  _ = error $ "[printFunctionLemmasAndProofs] invalid function " ++ show f ++ " with no CEBs"
printFunctionLemmasAndProofs f fReal field args stm acebs fp =
  vcat (zipWith (curry toDoc) [0..] acebs)
  $$
  text ""
  $$
  printAggregatedLemmasAndProofs f args (length acebs)
  where
    toDoc = printCEBLemmasAndProof f fReal field args stm fp

printAggregatedLemmasAndProofs :: String -> [Arg] -> Int -> Doc
printAggregatedLemmasAndProofs f args n
  = text f <> text "_error"
    <> argsTypedDoc
    <>  text ": nonneg_real"
    <+> text "=" <+>
         (if n==1 then text f <> text "_0_error" <> actArgsDoc
          else linearizeMax $ map errFunDoc [0..(n-1)])
    where
      argsTypedDoc = parens (hsep (punctuate comma $ map printParameterError args)
        <>  text ": nonneg_real" <> comma
        <+> hsep (punctuate comma $ map printParameterRealVariant args)
        <>  text ": real")
      actArgsDoc = parens (hsep (punctuate comma $ map printParameterError args)
        <> comma
        <+> hsep (punctuate comma $ map printParameterRealVariant args))
      errFunDoc m = text f <> text "_" <> int m <> text "_error" <> actArgsDoc

printCEBLemmasAndProof :: String -> String -> ResultField -> [Arg] -> FAExpr -> PVSType -> (Int,ACeb) -> Doc
printCEBLemmasAndProof f fReal field args stm fp (n,aceb)
  = prErrorDef f fReal field args aceb fp n
    $$
    text ""
    $$
    prPvsLemma f fReal field args aceb fp n (listFPGuardsFAExpr stm)
    $$
    text ""
    $$
    prPvsProof f n

prErrorDef :: String -> String -> ResultField -> [Arg] -> ACeb -> PVSType -> Int -> Doc
prErrorDef f _fReal _field           []    _ _fp _  = error $ "[prErrorDef] unexpected empty arguments for function " ++ show f
prErrorDef f _fReal _field args@(arg:_) aceb _fp n  =
  text f <> text "_" <> int n <> text "_error"
                     <+> parens ( hsep (punctuate comma $ map printParameterError args)
                                  <>  text ": nonneg_real" <> comma
                                  <+> hsep (punctuate comma $ map printParameterRealVariant args)
                                  <>  text ":" <+> printArgType arg
                                )
                     <>  text ": nonneg_real"
                     <+> text "=" <+> prettyError (fromMaybe (error "prPvsLemma: unexpected argument.") err)
  where
    ACeb {eExpr = err} = aceb

printArgType :: Arg -> Doc
printArgType (Arg _            _ ) = text "real"

prPvsLemma :: String -> String -> ResultField -> [Arg] -> ACeb -> PVSType -> Int -> [FAExpr] -> Doc
prPvsLemma f     _     _           []    _  _ _ _fpGuards = error $ "[prPvsLemma] unexpected empty arguments for function " ++ show f
prPvsLemma f fReal field args@(arg:_) aceb fp n _fpGuards =
  text f <> text "_" <> int n <+> text ": LEMMA"
  $$ text "∀(" <>  hsep (punctuate comma $ map printParameterError args)
                    <>  text ": nonneg_real" <> comma
                    <+> hsep (punctuate comma $ map printParameterRealVariant args)
                    <>  text ":" <+> printArgType arg <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args)
                    <> text ")" <> text ":"
  $$ printFinitenessConditions f args fp (fDeclRes $ fpExprs aceb)
  $$ text "AND"
  $$ prPvsArgsSymb args
  $$ (if isTrueCondition c then empty else text "AND" <+> parens (prettyDoc c))
  $$ text "IMPLIES"
  $$ printFunctionPartialBound f fReal field args fp n
  where
    ACeb {conds = c} = aceb

printFinitenessConditions :: String -> [Arg] -> PVSType -> [FAExpr] -> Doc
printFinitenessConditions f args ty fpResult =
  printAllArgumentsFiniteness
  $$
  text "AND"
  $$
  printSubExpressionsFiniteness fpResult
  $$
  text "AND"
  $$
  printFunctionFiniteness f args ty
  where
    printAllArgumentsFiniteness = vcat (intersperse (text "AND") $ map printArgumentFiniteness args)
      where
        printArgumentFiniteness (Arg x t) = finitePred t <> parens (text x)

finitePred :: PVSType -> Doc
finitePred          FPDouble = text "finite?_double"
finitePred                 t = error $ "[printFinitenessConditions:finitePred] unsupported type: " ++ show t

printSubExpressionsFiniteness :: [FAExpr] -> Doc
printSubExpressionsFiniteness fpResult = prIsFiniteHp subexps locVars
  where
    subexps = concatMap subExpressions fpResult
    locVars = concatMap localVars fpResult

printFunctionFiniteness :: String -> [Arg] -> PVSType -> Doc
printFunctionFiniteness f args ty =
  finitePred ty <> parens (
    text f <> parens (
      hcat $ intersperse comma $ map (\(Arg n _) -> text n) args
    )
  )

printFunctionPartialBound :: String -> String -> ResultField -> [Arg] -> PVSType -> Int -> Doc
printFunctionPartialBound f f_real field args ty n =
  printNorm ty <> parens (
      f2r ty
        (printNameWithField (text f <> text "(" <> hsep (punctuate comma $ map (prettyDoc . arg2var) args) <> text ")" ) field)
     <+> text "-"
     <+> printNameWithField (text f_real <> text "("
     <> hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args) <> text ")") field
  )
  <+>
  text "<="
  <+>
  text f <> text "_" <> int n <> text "_error" <> parens (
    hsep (punctuate comma $ map printParameterError args)
    <>
    comma
    <+>
    hsep (punctuate comma $ map printParameterRealVariant args)
  )

prPvsProof :: String -> Int -> Doc
prPvsProof f n =
    text "%|- " <> text f <> text "_" <> int n <> text ": PROOF"
    $$ text "%|- (precisa)"
    $$ text "%|- QED"

prIsFiniteHp :: [FAExpr] -> [(VarName, FAExpr)] -> Doc
prIsFiniteHp [] _ = emptyDoc
prIsFiniteHp isFiniteCheckList localVars' = prLocalVars localVars' isFiniteListDoc
  where
    isFiniteListDoc = hsep (punctuate (text " AND") (map prIsFinite isFiniteCheckList))

prPvsArgsSymb :: [Arg] -> Doc
prPvsArgsSymb = hsep . punctuate (text " AND") . map printArgumentBound

f2r :: PVSType -> Doc -> Doc
f2r fp doc = case fp of
  FPSingle -> text "StoR" <> parens doc
  FPDouble -> text "DtoR" <> parens doc
  TInt     -> doc
  Boolean  -> doc
  Array   _ FPSingle -> text "StoR" <> parens doc
  Array   _ FPDouble -> text "DtoR" <> parens doc
  Array   _        _ -> doc
  List  FPSingle -> text "StoR" <> parens doc
  List  FPDouble -> text "DtoR" <> parens doc
  List         _ -> doc
  TypeFun _ _ -> doc
  t -> error $ "f2r: something went wrong, f2r not defined for " ++ show t

prLocalVars :: [(VarName, FAExpr)] -> Doc -> Doc
prLocalVars [] doc = doc
prLocalVars locVarList doc =
  text "LET"
  <+> vcat (punctuate comma (map
       (\(varName, letExpr) -> text varName <> text "=" <> prettyDoc letExpr) locVarList))
        $$ text "IN" <+> parens doc

prIsFinite :: FAExpr -> Doc
prIsFinite ae | getPVSType ae == FPSingle = text "finite?_single" <> parens (prettyDoc ae)
              | getPVSType ae == FPDouble = text "finite?_double" <> parens (prettyDoc ae)
              | getPVSType ae == TInt = text "int_in_range?_double" <> parens (prettyDoc ae)
              | otherwise = error $ "prIsFinite: " ++ show ae ++ " is not a floating-point or integer expression."

printArgumentBound :: Arg -> Doc
printArgumentBound (Arg x (Tuple ts)) = vcat $ zipWith (curry (printArgumentBound . tuple2Arg)) ts indexes
  where
    tuple2Arg (idxType, idx) = Arg (x ++ "_" ++ show idx) idxType
    indexes = [1..] :: [Int]
printArgumentBound (Arg x (Record fs)) = vcat $ map (printArgumentBound . record2Arg) fs
  where
    record2Arg (field,fieldType) = Arg (x ++ "_" ++ field) fieldType
printArgumentBound arg@(Arg x t) =
  printNorm t <> parens (
    f2r t (text x)
    <+>
    text "-"
    <+>
    printParameterRealVariant arg
  )
  <+>
  text "<="
  <+>
  printParameterError arg

printNorm :: PVSType -> Doc
printNorm             FPDouble = text "abs"
printNorm                   ty = error $ "[printNorm] unimplemented norm for type: " ++ show ty

printParameterRealVariant :: Arg -> Doc
printParameterRealVariant  (Arg x _) = text "r_" <> text x

printParameterError :: Arg -> Doc
printParameterError (Arg x _) = text "e_" <> text x