-- Notices:
--
-- Copyright 2020 United States Government as represented by the Administrator of the National Aeronautics and Space Administration. All Rights Reserved.

-- Disclaimers
-- No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT SOFTWARE.  FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND DISTRIBUTES IT "AS IS."

-- Waiver and Indemnity:  RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT.  IF RECIPIENT'S USE OF THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW.  RECIPIENT'S SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL TERMINATION OF THIS AGREEMENT.


module PVSCert where

import AbsPVSLang hiding (fpGuardList,letExpr,varName)
import AbsSpecLang
import AbstractSemantics
import AbstractDomain
import AnalysisResult
import Common.ControlFlow
import Common.TypesUtils (VarName,PredAbs(..))
import Data.Maybe (fromMaybe)
import qualified Data.Map as Map
import Kodiak.Runner
import Numeric
import Prelude hiding ((<>))
import PPExt
import RelativeError (RelError(..))

genFpProgFile :: PVSType -> String -> Program -> Doc
genFpProgFile fp progFileName prog =
  text "% This file is automatically generated by PRECiSA \n"
  $$
  text (progFileName ++ ": THEORY")
  $$
  text "BEGIN" <> text "\n"
  $$
  importFPTheory fp <> text "\n"
  $$
  prettyDoc prog <> text "\n"
  $$
  text ("END " ++ progFileName)
    where
      importFPTheory FPSingle = text "IMPORTING float_bounded_axiomatic@ieee754_single"
      importFPTheory FPDouble = text "IMPORTING float_bounded_axiomatic@ieee754_double"
      importFPTheory _ = emptyDoc

genCertFile :: String -> String -> String -> Program -> Interpretation -> Bool -> Doc
genCertFile inputFileName certFileName realFileName prog sem relErr =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text (certFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text "IMPORTING PRECiSA@strategies"
  $$
  importRelErrTheory relErr
  $$
  text "IMPORTING float_bounded_axiomatic@aerr_ulp__double"
  $$
  text "IMPORTING float_bounded_axiomatic@aerr_ulp__single"
  $$
  text ("IMPORTING " ++ inputFileName)
  $$
  text ("IMPORTING " ++ realFileName  ++ "\n")
  $$
  text "%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED\n"
  $$
  printCerts relErr sem prog
  $$
  text ("END " ++ certFileName)

-- | @PRECiSA@relative_error@ is where 'relative_error_bound' lives, and the
--   bridge lemmas emitted by 'printCerts' are the only things that cite it.
--
--   It is therefore imported ONLY under @--relative-error@, and never from
--   @PRECiSA@strategies@: that theory is in the import chain of every
--   certificate PRECiSA has ever generated, so importing an UNVERIFIED theory
--   from it would drag it -- and its unproved TCC -- into the proof context of
--   users who never asked for a relative bound.
--
--   With the flag off this is 'emptyDoc', and @empty $$ d == d@, so the
--   generated text is byte-identical to what it was before the feature.
--
--   The NUMERIC certificate needs no import of its own: it does
--   @IMPORTING <name>_cert@ and so inherits this one transitively.
importRelErrTheory :: Bool -> Doc
importRelErrTheory True  = text "IMPORTING PRECiSA@relative_error"
importRelErrTheory False = emptyDoc

genRealProgFile :: PPExt a => String -> String -> a -> Doc
genRealProgFile inputFileName realProgFileName prog =
  text "% This file is automatically generated by PRECiSA \n"
  $$
  text (realProgFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text ("IMPORTING " ++ inputFileName ++ "\n")
  $$
  prettyDoc prog
  $$
  text ("END " ++ realProgFileName)

genNumCertFile :: String
               -> String
               -> [FunResult]
               -> [Decl]
               -> Spec
               -> Int
               -> Int
               -> Bool
               -> Doc
genNumCertFile certFileName numCertFileName kodiakResult decls (Spec specBinds) maxBBDepth prec isTran =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text ("% maxDepth: " ++ show maxBBDepth ++ " , prec: 10^-" ++ show prec ++ "\n")
  $$
  text (numCertFileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text ("IMPORTING " ++ certFileName)
  $$
  text "IMPORTING PRECiSA@bbiasp"
  $$
  text "IMPORTING PRECiSA@bbiadp"
  $$
  text "IMPORTING PRECiSA@strategies"
  $$
  text "%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED\n"
  $$
  printNumCerts kodiakResult decls specBinds maxBBDepth prec isTran
  $$
  text ("END " ++ numCertFileName)

printNumCerts :: [FunResult]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCerts [] _ _ _ _ _ = emptyDoc
printNumCerts (fr:res') decls spec maxBBDepth prec isTran
  | frType fr == Boolean = printNumCerts res' decls spec maxBBDepth prec isTran
  | otherwise =
      printNumCertsField (frName fr) (frType fr) (frArgs fr) (frFields fr) decls spec maxBBDepth prec isTran
      $$
      printNumCerts res' decls spec maxBBDepth prec isTran


printNumCertsField :: String
              -> PVSType
              -> [Arg]
              -> [(ResultField, [PathResult])]
              -> [Decl]
              -> [SpecBind]
              -> Int
              -> Int
              -> Bool
              -> Doc
printNumCertsField _ _ _ [] _ _ _ _ _ = emptyDoc
printNumCertsField f t args ((field,res):res') decls spec maxBBDepth prec isTran =
  printNumCertsFun fFP fReal field args res ranges 0 fp prec maxBBDepth isTran fpGuardList
  $$
  printNumCertsField f t args res' decls spec maxBBDepth prec isTran
  where
    fp = case t of
      Tuple ts -> case field of
                      ResTupleIndex idx -> ts !! fromInteger (idx - 1)
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid tuple index."
      Record ts -> case field of
                      ResRecordField rField -> fromMaybe (error $ "printCertsField: field " ++ show rField ++ " not found.")
                                              $ lookup rField ts
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid record field."
      _ -> t
    fpGuardList = case findInDecls f decls of
                     Just (_,_,body@(AExprBody _ae)) -> listFPGuards body
                     Just (_,_,body@(CExprBody _ae)) -> listFPGuards body
                     Just (_,_,BExprBody _) -> error $ "printNumCerts: function " ++ f ++ " is of type Boolean."
                     Nothing -> error $ "printNumCerts: function " ++ f ++ " not found."
    ranges = fromMaybe (error $ "printNumCerts: function " ++ show f ++ " not found.") (findInSpec f spec)
    fFP   = if isTran then f ++ "_fp" else f
    fReal = if isTran then f else f ++ "_real"

printNumCertsFun :: String
                 -> String
                 -> ResultField
                 -> [Arg]
                 -> [PathResult]
                 -> [VarBind]
                 -> Int
                 -> PVSType
                 -> Int
                 -> Int
                 -> Bool
                 -> [FAExpr]
                 -> Doc
printNumCertsFun _ _ _ _ [] _ _ _ _ _ _ _ = emptyDoc
printNumCertsFun f fReal field args (pr:result') ranges n fp prec maxBBDepth isTran fpGuardList =
  prPvsNumLemma numLemma f fReal field args cond roundOffError ranges fp Nothing fpGuardList
  $$
  prPvsNumProof numLemma symbLemma prec maxBBDepth
  $$
  (case prRelError pr of
     RelErrorBound (RelFinite relBound) ->
       prPvsNumRelLemma numRelLemma f fReal field args cond relBound ranges fp fpGuardList
       $$
       prPvsNumRelProof numRelLemma symbRelLemma relBound prec maxBBDepth
     -- Nothing is emitted otherwise. For 'RelInfinite' there is no finite
     -- constant to instantiate 'rel' with, and for a failure -- or for the
     -- feature being off -- no bound was ever established: emitting a lemma
     -- would present a tool failure as a proved result.
     _ -> emptyDoc)
  $$
  (if isTran
     then prPvsNumLemma auxLemmaName f fReal field args cond roundOffError ranges fp (Just err) fpGuardList
     else emptyDoc)
  $$
  printNumCertsFun f fReal field args result' ranges (n+1) fp prec maxBBDepth isTran fpGuardList
  where
    cond = prConds pr
    err = prErrExpr pr
    auxLemmaName = name field <> text "_err_" <> int n
    numLemma = name field <> text "_c_" <> int n
    roundOffError = maximumUpperBound (prKodiak pr)
    symbLemma = name field <> text "_" <> int n
    numRelLemma  = name field <> text "_rel_c_" <> int n
    symbRelLemma = name field <> text "_rel_" <> int n
    name ResValue = text f
    name (ResRecordField recField) = text f <> text "_" <> text recField
    name (ResTupleIndex tupleIdx) = text f <> text "_" <> integer tupleIdx

printCertsField :: Bool
                -> FunName
                -> Bool
                -> PVSType
                -> FAExpr
                -> [Arg]
                -> ResultField
                -> ACebS
                -> Doc
                -> Doc
printCertsField relErr f isTrans t stm args field cset certDocField
  = printLemmasAndProofs relErr fFP fReal field args stm cset fp 0
    $$ certDocField
  where
    fp = case t of
      Tuple ts -> case field of
                      ResTupleIndex idx -> ts !! fromInteger (idx - 1)
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid tuple index."
      Record ts -> case field of
                      ResRecordField rField -> fromMaybe (error $ "printCertsField: field " ++ show rField ++ " not found.")
                                              $ lookup rField ts
                      _ -> error $ "printCertsField: " ++ show field ++ " is not a valid record field."
      _ -> t
    fFP   = if isTrans then f ++ "_fp" else f
    fReal = if isTrans then f else f ++ "_real"

printCerts :: Bool -> Interpretation -> Program -> Doc
printCerts relErr interp decls = Map.foldrWithKey printCertsFun emptyDoc interp
  where
    printCertsFun _ (_,Boolean, _, _) certDoc = certDoc
    printCertsFun f (isTrans,t, args, sem) certDoc = case findInDecls f decls of
      Just (_,_,AExprBody stm) -> Map.foldrWithKey (printCertsField relErr f isTrans t stm args) certDoc sem
      _ -> error $ "printCerts: function " ++ show f ++ " not found."

printLemmasAndProofs :: Bool -> String -> String -> ResultField -> [Arg] -> FAExpr -> ACebS -> PVSType -> Int -> Doc
printLemmasAndProofs _relErr f _ _ args _ [] _ n
  = text f <> text "_error"
    <> argsTypedDoc
    <>  text ": nonneg_real"
    <+> text "=" <+>
         (if n==1 then text f <> text "_0_error" <> actArgsDoc
          else linearizeMax $ map errFunDoc [0..(n-1)])
    <> text "\n"
    where
      prRealInt  (Arg x _) = text "r_" <> text x
      prErrorInt (Arg x _) = text "e_" <> text x
      argsTypedDoc = parens (hsep (punctuate comma $ map prErrorInt args)
        <>  text ": nonneg_real" <> comma
        <+> hsep (punctuate comma $ map prRealInt args)
        <>  text ": real")
      actArgsDoc = parens (hsep (punctuate comma $ map prErrorInt args)
        <> comma
        <+> hsep (punctuate comma $ map prRealInt args))
      errFunDoc m = text f <> text "_" <> int m <> text "_error" <> actArgsDoc

printLemmasAndProofs relErr f fReal field args stm (aceb:acebs) fp n
  = prErrorDef f fReal field args aceb fp n
    $$
    prPvsLemma f fReal field args aceb fp n (listFPGuardsFAExpr stm)
    $$
    prPvsProof f n
    $$
    (if relErr
       then prPvsRelLemma f fReal field args aceb fp n (listFPGuardsFAExpr stm)
            $$ prPvsRelProof f n
       else emptyDoc)
    $$
    printLemmasAndProofs relErr f fReal field args stm acebs fp (n+1)

prPvsProof :: String -> Int -> Doc
prPvsProof f n =
    text "%|- " <> text f <> text "_" <> int n <> text ": PROOF"
    $$ text "%|- (precisa)"
    $$ text "%|- QED"
    $$ text "\n"

prPvsRelProof :: String -> Int -> Doc
prPvsRelProof f n =
    text "%|- " <> text f <> text "_rel_" <> int n <> text ": PROOF"
    $$ text "%|- " <> parens (text "prove-symbolic-relative-lemma"
                              <+> text f <> text "_" <> int n)
    $$ text "%|- QED"
    $$ text "\n"

prIsFinite :: FAExpr -> Doc
prIsFinite ae | getPVSType ae == FPSingle = text "finite?_single" <> parens (prettyDoc ae)
              | getPVSType ae == FPDouble = text "finite?_double" <> parens (prettyDoc ae)
              | getPVSType ae == TInt = text "int_in_range?_double" <> parens (prettyDoc ae)
              | otherwise = error $ "prIsFinite: " ++ show ae ++ " is not a floating-point or integer expression."

prIsFiniteHp :: [FAExpr] -> [(VarName, FAExpr)] -> Doc
prIsFiniteHp [] _ = emptyDoc
prIsFiniteHp isFiniteCheckList localVars' = prLocalVars localVars' isFiniteListDoc
  where
    isFiniteListDoc = hsep (punctuate (text " AND") (map prIsFinite isFiniteCheckList))

prLocalVars :: [(VarName, FAExpr)] -> Doc -> Doc
prLocalVars [] doc = doc
prLocalVars locVarList doc =
  text "LET"
  <+> vcat (punctuate comma (map
       (\(varName, letExpr) -> text varName <> text "=" <> prettyDoc letExpr) locVarList))
        $$ text "IN" <+> parens doc

prErrorDef :: String -> String -> ResultField -> [Arg] -> ACeb -> PVSType -> Int -> Doc
prErrorDef f _fReal _field args aceb _fp n  =
  text f <> text "_" <> int n <> text "_error"
                     <+> parens (hsep (punctuate comma $ map prErrorInt args)
                     <>  text ": nonneg_real" <> comma
                     <+> hsep (punctuate comma $ map prRealInt args)
                     <>  text ": real")
                     <>  text ": nonneg_real"
                     <+> text "=" <+> prettyError (fromMaybe (error "prPvsLemma: unexpected argument.") err)
  $$ text "\n"
  where
    prRealInt  (Arg x _) = text "r_" <> text x
    prErrorInt (Arg x _) = text "e_" <> text x
    ACeb {eExpr = err} = aceb

-- | The hypothesis block of the absolute error lemma. It is shared verbatim
--   with the relative error bridge lemma ('prPvsRelLemma'), which is proved by
--   citing the absolute lemma: the two MUST carry exactly the same hypotheses,
--   or the bridge lemma is both unprovable and false (nothing would rule out
--   an overflowing floating-point result).
prPvsLemmaHyps :: [Arg] -> ACeb -> Doc
prPvsLemmaHyps args aceb =
     prIsFiniteHp isFiniteExprs locVars
  $$ text "AND"
  $$ prPvsArgsSymb args
  $$ (if isTrueCondition c then empty else text "AND" <+> parens (prettyDoc c))
  where
    isFiniteExprs = concatMap subExpressions (fDeclRes $ fpExprs aceb)
    locVars = concatMap localVars (fDeclRes $ fpExprs aceb)
    ACeb {conds = c} = aceb

-- | The error function applied to the symbolic error and real arguments,
--   i.e. the right-hand side of the absolute error lemma.
prErrFunApp :: String -> [Arg] -> Int -> Doc
prErrFunApp f args n =
  text f <> text "_" <> int n <> text "_error"
  <> parens (hsep (punctuate comma $ map prErrorInt args)
             <> comma
             <+> hsep (punctuate comma $ map prRealInt args))
  where
    prRealInt  (Arg x _) = text "r_" <> text x
    prErrorInt (Arg x _) = text "e_" <> text x

-- | The application of the real-valued function to the real arguments.
prRealFunApp :: String -> ResultField -> [Arg] -> Doc
prRealFunApp fReal field args =
  printNameWithField (text fReal <> text "("
  <> hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args)
  <> text ")") field

-- | The absolute distance between the floating-point and the real result.
prDivergence :: String -> String -> ResultField -> [Arg] -> PVSType -> Doc
prDivergence f fReal field args fp =
  text "abs(" <> f2r fp (printNameWithField (text f <> text "(" <>
  hsep (punctuate comma $ map (prettyDoc . arg2var) args) <> text ")" ) field)
  <+> text "-"
  <+> prRealFunApp fReal field args
  <> text ")"

prPvsLemma :: String -> String -> ResultField -> [Arg] -> ACeb -> PVSType -> Int -> [FAExpr] -> Doc
prPvsLemma f fReal field args aceb fp n _fpGuards =
  text f <> text "_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prErrorInt args)
                    <>  text ": nonneg_real" <> comma
                    <+> hsep (punctuate comma $ map prRealInt args)
                    <>  text ": real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args)
                    <> text ")" <> text ":"
  $$ prPvsLemmaHyps args aceb
  $$ text "IMPLIES"
  $$ prDivergence f fReal field args fp
     <+> text "<=" <+> prErrFunApp f args n
  $$ text "\n"
  where
    prRealInt  (Arg x _) = text "r_" <> text x
    prErrorInt (Arg x _) = text "e_" <> text x

-- | Range-free bridge lemma for the relative error. 'rel' is universally
--   quantified and the ratio bound is a hypothesis, so the statement is
--   multiplicative and carries no division TCC. The numeric certificate
--   instantiates 'rel' with the computed constant.
--
--   The lemma is proved by citing the absolute error lemma 'prPvsLemma'
--   generates for the same path, so it MUST repeat that lemma's hypotheses
--   verbatim -- hence the shared 'prPvsLemmaHyps'. Dropping them would make the
--   statement not merely unprovable but false: with no finiteness hypothesis
--   the floating-point result may overflow while the symbolic error stays
--   small.
prPvsRelLemma :: String -> String -> ResultField -> [Arg] -> ACeb -> PVSType -> Int -> [FAExpr] -> Doc
prPvsRelLemma f fReal field args aceb fp n _fpGuards =
  text f <> text "_rel_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prErrorInt args)
                    <>  text ": nonneg_real" <> comma
                    <+> hsep (punctuate comma $ map prRealInt args)
                    <>  text ": real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args)
                    <>  comma
                    <+> text "rel: real"
                    <> text ")" <> text ":"
  $$ prPvsLemmaHyps args aceb
  $$ text "AND"
  $$ prErrFunApp f args n <+> text "<=" <+> relBoundDoc
  $$ text "IMPLIES"
  $$ prDivergence f fReal field args fp <+> text "<=" <+> relBoundDoc
  $$ text "\n"
  where
    prRealInt  (Arg x _) = text "r_" <> text x
    prErrorInt (Arg x _) = text "e_" <> text x
    relBoundDoc = text "rel" <+> text "*"
                  <+> text "abs(" <> prRealFunApp fReal field args <> text ")"

prInfoLemma :: ControlFlow -> [FAExpr] -> [AExpr] -> Doc
prInfoLemma cflow fpes reales = text "% Floating-Point Results:"<+> hsep (punctuate comma $ map prettyDoc fpes)
  $$
  text "% Real Results:"<+> hsep (punctuate comma $ map prettyDoc reales)
  $$
  text "% Control Flow: "<+> prettyDoc cflow

prPvsNumProof :: Doc -> Doc -> Int -> Int -> Doc
prPvsNumProof numLemma symbLemma prec maxBBDepth =
     text "%|-" <+> numLemma <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-concrete-lemma" <+> symbLemma <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

prPvsNumLemma :: Doc
                -> String
                -> String
                -> ResultField
                -> [Arg]
                -> Conditions
                -> Double
                -> [VarBind]
                -> PVSType
                -> Maybe AExpr
                -> [FAExpr]
                -> Doc
prPvsNumLemma nameLemma f fReal field args cond roundOffError ranges fp symbError _fpGuards =
  nameLemma <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args)
                    <>  text ": real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args) <> text ")" <> text ":"
  $$ prPvsArgs args
  $$ (if isTrueCondition cond then empty else text "AND" <+> parens (prettyDoc cond))
  <+> text "AND"
  $$ hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ lhs
  <+> text "<="
  <+> prettyRatNumError roundOffError <> text "\n"
  where
    divergence =  text "abs("
      <>  f2r fp (printNameWithField (text f <> text "("
      <>  hsep (punctuate comma $ map (prettyDoc . arg2var) args) <> text ")") field)
      <+> text "-"
      <+> printNameWithField (text fReal <> text "("
      <>  hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args) <> text ")") field
      <>  text ")"
    lhs = maybe divergence prettyDoc symbError

-- | Numeric relative error lemma. This is the range-free bridge lemma
--   'prPvsRelLemma' with 'rel' instantiated to the constant Kodiak computed,
--   so the hypotheses here are the NUMERIC ones (argument ranges and the path
--   condition), matching 'prPvsNumLemma'.
--
--   The bound stays multiplicative, exactly as in 'prPvsRelLemma': stating it
--   as a quotient would generate a nonzero-divisor TCC, which the whole
--   certificate design avoids.
prPvsNumRelLemma :: Doc
                 -> String
                 -> String
                 -> ResultField
                 -> [Arg]
                 -> Conditions
                 -> Double
                 -> [VarBind]
                 -> PVSType
                 -> [FAExpr]
                 -> Doc
prPvsNumRelLemma nameLemma f fReal field args cond relBound ranges fp _fpGuards =
  nameLemma <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map (prettyDoc . realVar . arg2var) args)
                    <>  text ": real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc args) <> text ")" <> text ":"
  $$ prPvsArgs args
  $$ (if isTrueCondition cond then empty else text "AND" <+> parens (prettyDoc cond))
  <+> text "AND"
  $$ hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ prDivergence f fReal field args fp
  <+> text "<="
  <+> relBoundDoc <> text "\n"
  where
    relBoundDoc = prettyRatNumError relBound <+> text "*"
                  <+> text "abs(" <> prRealFunApp fReal field args <> text ")"

-- | Proof script for 'prPvsNumRelLemma'. It cites the symbolic bridge lemma
--   for the same path, mirroring how 'prPvsNumProof' cites the symbolic
--   absolute lemma.
--
--   Unlike the absolute lemma, the bridge lemma quantifies over 'rel', and
--   after skolemising the numeric goal there is no @rel@ in the sequent to
--   instantiate it with. PRECiSA knows the constant here, so it is passed to
--   the strategy as a quoted PVS term rather than recovered from the goal.
--   It is printed with the very same 'prettyRatNumError' that prints the
--   constant in 'prPvsNumRelLemma': the two MUST be character-for-character
--   identical, or the instantiated bridge lemma will not match the goal and
--   the proof cannot close.
--
--   UNVERIFIED: the @prove-relative-lemma@ strategy this emits has never been
--   run, as no PVS installation was available.
prPvsNumRelProof :: Doc -> Doc -> Double -> Int -> Int -> Doc
prPvsNumRelProof numLemma symbLemma relBound prec maxBBDepth =
     text "%|-" <+> numLemma <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-relative-lemma" <+> symbLemma
                            <+> doubleQuotes (prettyRatNumError relBound)
                            <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

prPvsArgsSymb :: [Arg] -> Doc
prPvsArgsSymb arguments = hsep $ punctuate (text " AND") $ map prPVSVarIdSymb arguments

prPVSVarIdSymb :: Arg -> Doc
prPVSVarIdSymb (Arg x (Tuple ts)) = vcat $ zipWith (curry (prPVSVarIdSymb . tuple2Arg)) ts indexes
  where
    tuple2Arg (idxType, idx) = Arg (x ++ "_" ++ show idx) idxType
    indexes = [1..] :: [Int]
prPVSVarIdSymb (Arg x (Record fs)) = vcat $ map (prPVSVarIdSymb . record2Arg) fs
  where
    record2Arg (field,fieldType) = Arg (x ++ "_" ++ field) fieldType
prPVSVarIdSymb (Arg x t) = text "abs(" <> f2r t (text x)
                               <+> text "-" <+> text "r_" <> text x <> text ")"
                               <> text "<=" <> text "e_" <> text x

prPvsArgs :: [Arg] -> Doc
prPvsArgs arguments = hsep $ punctuate (text " AND") $ map (uncurry prPVSVarId . mapArg2Pair) arguments

prPVSVarId :: VarName -> PVSType -> Doc
prPVSVarId _ (TypeFun _ _) = empty
prPVSVarId x (Tuple ts) = vcat $ zipWith (curry (uncurry prPVSVarId . tuple2Arg)) ts indexes
  where
    tuple2Arg (idxType, idx) = (x ++ "_" ++ show idx, idxType)
    indexes = [1..] :: [Int]
prPVSVarId x (Record fs) = vcat $ map (uncurry prPVSVarId . record2Arg) fs
  where
    record2Arg (field,fieldType) = (x ++ "_" ++ field, fieldType)
prPVSVarId x TInt = text "abs("<> text x <+> text "-" <+> text "r_" <> text x <> text ")" <> text "<= 0"
prPVSVarId x fpx  = text "abs(" <> f2r fpx (text x)
                       <+> text "-" <+> text "r_" <> text x <> text ")"
                       <> text "<=" <> prettyDoc (HalfUlp (RealMark x ResValue) fpx)

printVarRange :: VarBind -> Doc
printVarRange (VarBind x ResValue _ lb ub) =
  text "r_" <> text x <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"
printVarRange (VarBind x (ResRecordField field) _ lb ub) =
  text "r_" <> text x <> text "`" <> text field <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"
printVarRange (VarBind x (ResTupleIndex idx) _ lb ub) =
  text "r_" <> text x <> text "`" <> integer idx <+> text "##" <+> text "[|" <> prettyDoc lb <> comma <> prettyDoc ub <> text "|]"

prettyRatNumError :: RealFloat a => a -> Doc
prettyRatNumError roundOffError = text $ showRational (toRational roundOffError )

prettyNumError :: RealFloat a => a -> Doc
prettyNumError roundOffError = text $ showFFloat Nothing roundOffError "" -- (nextUp' roundOffError) ""

f2r :: PVSType -> Doc -> Doc
f2r fp doc = case fp of
  FPSingle -> text "StoR" <> parens doc
  FPDouble -> text "DtoR" <> parens doc
  TInt -> doc
  Boolean -> doc
  Array _ FPSingle -> text "StoR" <> parens doc
  Array _ FPDouble -> text "DtoR" <> parens doc
  Array _ _ -> doc
  List  FPSingle -> text "StoR" <> parens doc
  List  FPDouble -> text "DtoR" <> parens doc
  List  _ -> doc
  TypeFun _ _ -> doc
  t -> error $ "f2r: something went wrong, f2r not defined for " ++ show t

genExprCertFile :: PVSType -> String -> String -> String -> Doc -> Doc
genExprCertFile fp inputFileName fpFileName fileName printTranProgPairs =
  text "% This file is automatically generated by PRECiSA"
  $$
  text "%"
  $$
  text (fileName ++ ": THEORY")
  $$
  text "BEGIN"
  $$
  text "IMPORTING" <+> ieeeFormalization fp <> text ", PRECiSA@strategies, PRECiSA@bbiasp, PRECiSA@bbiadp,"
  <+>
  text inputFileName
  <>
  comma
  <+>
  text fpFileName
  $$
  text "\n%|- *_TCC* : PROOF"
  $$
  text "%|- (precisa-gen-cert-tcc)"
  $$
  text "%|- QED\n"
  $$
  printTranProgPairs
  $$
  text ("\nEND " ++ fileName)
  where
    ieeeFormalization FPDouble = text "float_bounded_axiomatic@ieee754_double"
    ieeeFormalization FPSingle = text "float_bounded_axiomatic@ieee754_single"
    ieeeFormalization t = error $ "genExprCertFile: PVS type " ++ show t ++ " not supported."

prIsFiniteHpExpr :: [FAExpr] -> Doc
prIsFiniteHpExpr [] = emptyDoc
prIsFiniteHpExpr aes = text "AND"
                       $$ hsep (punctuate (text " AND") (map prIsFinite aes))

printSymbExprCert :: PVSType -> String -> [FAExpr] -> [AExpr] -> [AExpr] -> FAExpr -> AExpr -> FBExpr -> EExpr -> Int -> Doc
printSymbExprCert fp f faeVarList errVarList realVarList fae ae be symbErr n =
  text f <> text "_expr_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prettyVarWithType faeVarList)
                    <> comma
                    <+> hsep (punctuate comma $ map prettyDoc errVarList)
                    <>  text ": nonneg_real" <> comma
                    <+> hsep (punctuate comma $ map prettyDoc realVarList)
                    <>  text ": real"
                    <> text ")" <> text ":"
  $$ hsep (punctuate (text " AND") (map (printVarErrBound fp) faeVarList))
  $$ text "AND" <+> parens (prettyDoc be)
  -- $$ prIsFiniteHpExpr (fae:faeVarList)
  $$ text "IMPLIES"
  $$ text "abs(" <> f2r fp (prettyDoc fae)
     <+> text "-"
     <+> prettyDoc ae <> text ")"
     <+> text "<="
     <+> prettyError symbErr
  $$ text "\n%|- " <> text f <> text "_" <> int n <> text ": PROOF"
  $$ text "%|- (precisa)"
  $$ text "%|- QED"
  $$ text "\n"

printNumExprCert :: PVSType -> String -> [FAExpr] -> [AExpr] -> FAExpr -> AExpr -> FBExpr -> Double -> [VarBind] -> Int -> Int -> Int -> Doc
printNumExprCert fp f faeVarList realVarList fae ae be roundOffError ranges n maxBBDepth prec  =
  text f <> text "_expr_num_" <> int n <+> text ": LEMMA"
  $$ text "FORALL(" <>  hsep (punctuate comma $ map prettyVarWithType faeVarList)
                    <>  comma
                    <+> hsep (punctuate comma $ map prettyDoc realVarList)
                    <>  text ": real"
                    <>  text ")" <> text ":"
  $$ hsep (punctuate (text " AND") $ map (uncurry prPVSVarId . (\a -> (nameFVar a, precFVar a))) faeVarList)
  $$ text "AND"
  <+> parens (prettyDoc be)
  $$ text "AND" <+> hsep (punctuate (text " AND ") $ map printVarRange ranges)
  $$ text "IMPLIES"
  $$ text "abs(" <> f2r fp (prettyDoc fae)
     <+> text "-"
     <+> prettyDoc ae <> text ")"
     <+> text "<="
  <> prettyRatNumError roundOffError  <> text "\n"
  $$ text "%|-" <+> text f <> text "_c_" <> int n <+> text ": PROOF"
  $$ text "%|-" <+> parens (text "prove-concrete-lemma" <+> text f <> text "_expr_" <> int n <+> int prec <+> int maxBBDepth)
  $$ text "%|- QED\n"

printVarErrBound :: PVSType -> FAExpr -> Doc
printVarErrBound fp var@(FVar _ _) = text "abs(" <> f2r fp (prettyDoc var)
                                                 <> text "-"
                                                 <> prettyDoc (realVar var)
                                                 <> text ")<=" <> prettyDoc (errVar var)
printVarErrBound _ ae = error $ "printVarErrBound: case " ++ show ae ++ " not expected."

printExprFunCert :: Int -> Int -> PVSType -> (Decl, [(VarName,FAExpr,AExpr,FBExpr,EExpr,Double,[FAExpr],[AExpr],[EExpr],[VarBind])]) -> Doc
printExprFunCert maxDepth minPrec fp (Decl _ _ f _ _, exprList) = vcat $ zipWith (printExprCert' maxDepth minPrec fp f) exprList [1 :: Int, 2 ..]
printExprFunCert        _       _ _ (Pred _ TauMinus _ _ _, _) = emptyDoc
printExprFunCert maxDepth minPrec fp (Pred _ _ f _ _, exprList) = vcat $ zipWith (printExprCert' maxDepth minPrec fp f) exprList [1 :: Int, 2 ..]
printExprFunCert _ _ _ x = error $ "[printExprFunCert] Unhandled case: " ++ show x

printExprCert' :: Int -> Int -> PVSType -> String -> (VarName,FAExpr,AExpr,FBExpr,EExpr,Double,[FAExpr],[AExpr],[EExpr],[VarBind]) -> Int -> Doc
printExprCert' maxDepth minPrec fp f (_,fae, ae, be, symbErr, numErr, faeVarList, realVarList, errVarList,varBinds) n =
  printSymbExprCert fp f faeVarList errVarList realVarList fae ae be symbErr n
  $$
  printNumExprCert fp f faeVarList realVarList fae ae be numErr varBindsRestricted n maxDepth minPrec
  where
    varBindsRestricted = filter (isVarInList (map fvarName faeVarList)) varBinds
    isVarInList vars (VarBind x _ _ _ _) = x `elem` vars
